- name: Install needed packages
  apt:
    state: present
    name:
      - git
      - python3
      - python3-pip

- name: Install pipenv
  pip:
    executable: pip3
    name: pipenv
    state: latest

- name: Fetch code from github
  become_user: pi
  git:
    repo: https://github.com/davea/radcontrold.git
    dest: /home/pi/radcontrold
  notify:
    - restart radcontrold

- name: Set up radcontrold pipenv
  become_user: pi
  shell: pipenv --bare install
  args:
    chdir: "/home/pi/radcontrold"
  environment:
    LANG: en_GB.UTF-8
    LC_ALL: en_GB.UTF-8
    PIPENV_TIMEOUT: 240
  notify:
    - restart radcontrold

- name: Setup config dir
  file:
    path: /home/pi/.config/radcontrold
    state: directory
    owner: pi
    group: pi
  tags:
    - radcontrold.config

- name: Install radcontrold configuration
  template:
    src: radcontrold.ini.j2
    dest: /home/pi/.config/radcontrold/{{ item.hostname }}.ini
    owner: pi
    group: pi
  with_items: "{{ radcontrold.hosts }}"
  notify:
    - restart radcontrold
  tags:
    - radcontrold.config

- name: Create systemd units
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
  with_items:
    - radcontrold.service
    - radcontrold_health_check.service
    - radcontrold_health_check.timer
  notify:
    - restart radcontrold

- name: Enable systemd service
  systemd:
    enabled: yes
    state: started
    name: radcontrold.service
    daemon_reload: yes

- name: Enable systemd health check service
  systemd:
    enabled: yes
    name: radcontrold_health_check.timer
    daemon_reload: yes
